//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface NSViewAnimationContext : NSObject

@property (nonatomic, readonly) void(^completionHandler)(BOOL finished);
@property (nonatomic) NSInteger animationCount;
@property (nonatomic, strong) NSArray *viewAnimations;
- (id)initWithCompletionHandler:(void(^)(BOOL))arg1;

@end

