//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSArray;

@interface NSViewAnimationContext : NSObject
{
    NSArray *_viewAnimations;
    long long _animationCount;
    void(^_completionHandler)(BOOL finished);
}

@property(readonly, nonatomic) void(^completionHandler)(BOOL finished); // @synthesize completionHandler=_completionHandler;
@property(nonatomic) long long animationCount; // @synthesize animationCount=_animationCount;
@property(retain, nonatomic) NSArray *viewAnimations; // @synthesize viewAnimations=_viewAnimations;
- (id)initWithCompletionHandler:(void(^)(BOOL))arg1;

@end

