//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXView.h>
#import <UXKit/UXBarPositioning-Protocol.h>

@interface UXBar : UXView <NSAccessibilityGroup, UXBarPositioning>

@property (nonatomic, strong) UXView *nextItemContainer; // @synthesize nextItemContainer=_nextItemContainer;
@property (nonatomic) double percent; // @synthesize percent=_percent;
@property (nonatomic) BOOL isInteractiveTransitioning; // @synthesize isInteractiveTransitioning=_isInteractiveTransitioning;
@property (nonatomic, strong) UXView *barItemsContainer; // @synthesize barItemsContainer=_barItemsContainer;
@property (nonatomic) double height; // @synthesize height=_height;
@property (nonatomic) double interitemSpacing; // @synthesize interitemSpacing=_interitemSpacing;
@property (nonatomic, strong) NSColor *barTintColor; // @synthesize barTintColor=_barTintColor;
@property (nonatomic, readonly) long long barPosition;
- (CGSize)intrinsicContentSize;
@property (nonatomic, strong) NSColor *borderColor;
@property (nonatomic) BOOL bordered;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

