//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface UXBarItem : NSObject

@property (nonatomic) long long tag; // @synthesize tag=_tag;
@property (nonatomic, strong) NSImage *image; // @synthesize image=_image;
@property (nonatomic, copy) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
@property (nonatomic, strong) NSString *title; // @synthesize title=_title;
@property (nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
- (id)init;

@end

