//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXBarItem.h>
#import <UXKit/UXKitAppearance-Protocol.h>

@class UXViewController;

@interface UXBarButtonItem : UXBarItem <UXKitAppearance>

@property (nonatomic) NSUInteger keyEquivalentModifierMask; // TODO: enum
@property (nonatomic, strong) NSString *keyEquivalent;
@property (nonatomic, strong) NSString *toolTip;
@property (nonatomic, weak) id target;
@property (nonatomic) SEL action;
@property (nonatomic, strong) NSView *customView;
- (void)setImage:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)setTitle:(id)arg1;
- (void)tintColorDidChange;
@property (nonatomic) CGFloat width;
@property (nonatomic) NSInteger style; // TODO: enum
@property (nonatomic) NSInteger tintAdjustmentMode; // TODO: enum
@property (nonatomic, strong) NSColor *tintColor;
- (id)initWithStyle:(NSInteger)arg1 target:(id)arg2 action:(SEL)arg3; // TODO: enum
- (id)initWithContentViewController:(id)arg1;
- (id)initWithCustomView:(id)arg1;
- (id)initWithBarButtonSystemItem:(NSInteger)arg1 target:(id)arg2 action:(SEL)arg3; // TODO: enum
- (id)initWithTitle:(id)arg1 style:(NSInteger)arg2 target:(id)arg3 action:(SEL)arg4; // TODO: enum
- (id)initWithImage:(id)arg1 style:(NSInteger)arg2 target:(id)arg3 action:(SEL)arg4; // TODO: enum

@end

