//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXCollectionView, UXCollectionViewLayout;

@interface UXCollectionViewData : NSObject

@property (nonatomic, readonly) NSArray *clonedLayoutAttributes; // @synthesize clonedLayoutAttributes=_clonedLayoutAttributes;
@property (nonatomic, getter=isLayoutLocked) BOOL layoutLocked;
@property (nonatomic, readonly) BOOL layoutIsPrepared;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)knownDecorationElementKinds;
- (id)knownSupplementaryElementKinds;
- (id)existingSupplementaryLayoutAttributes;
- (id)existingSupplementaryLayoutAttributesInSection:(long long)arg1;
- (id)layoutAttributesForElementsInRect:(CGRect)arg1;
- (id)layoutAttributesForElementsInSection:(long long)arg1;
- (id)layoutAttributesForGlobalItemIndex:(long long)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (CGRect)rectForDecorationElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (CGRect)rectForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (CGRect)rectForGlobalItemIndex:(long long)arg1;
- (CGRect)collectionViewContentRect;
- (CGRect)rectForItemAtIndexPath:(id)arg1;
- (id)indexPathForItemAtGlobalIndex:(long long)arg1;
- (long long)globalIndexForItemAtIndexPath:(id)arg1;
- (long long)numberOfItemsBeforeSection:(long long)arg1;
- (long long)numberOfItemsInSection:(long long)arg1;
- (long long)numberOfItems;
- (long long)numberOfSections;
- (void)validateLayoutInRect:(CGRect)arg1;
- (void)invalidate:(BOOL)arg1;
- (void)validateSupplementaryViews;
- (void)invalidateSupplementaryViews:(id)arg1;
- (id)initWithCollectionView:(id)arg1 layout:(id)arg2;

@end

