//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewLayout.h>

@interface UXCollectionViewFlowLayout : UXCollectionViewLayout

+ (Class)invalidationContextClass;
@property (nonatomic) NSEdgeInsets sectionInset; // @synthesize sectionInset=_sectionInset;
@property (nonatomic) CGSize footerReferenceSize; // @synthesize footerReferenceSize=_footerReferenceSize;
@property (nonatomic) CGSize headerReferenceSize; // @synthesize headerReferenceSize=_headerReferenceSize;
@property (nonatomic) CGSize itemSize; // @synthesize itemSize=_itemSize;
@property (nonatomic) double minimumInteritemSpacing; // @synthesize minimumInteritemSpacing=_interitemSpacing;
@property (nonatomic) double minimumLineSpacing; // @synthesize minimumLineSpacing=_lineSpacing;
@property (nonatomic) long long scrollDirection;
- (id)layoutAttributesForElementsInRect:(CGRect)arg1;
- (id)indexPathsForItemsInRect:(CGRect)arg1;
- (BOOL)shouldUpdateVisibleCellLayoutAttributes;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForFooterInSection:(long long)arg1;
- (id)layoutAttributesForHeaderInSection:(long long)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1 usingData:(id)arg2;
- (id)layoutAttributesForFooterInSection:(long long)arg1 usingData:(id)arg2;
- (id)layoutAttributesForHeaderInSection:(long long)arg1 usingData:(id)arg2;
- (id)indexPathOfItemAfter:(id)arg1;
- (id)indexPathOfItemBefore:(id)arg1;
- (id)indexPathOfItemAbove:(id)arg1;
- (id)indexPathOfItemBelow:(id)arg1;
- (id)indexPathForItemAtPoint:(CGPoint)arg1;
- (id)indexesForSectionFootersInRect:(CGRect)arg1;
- (id)indexesForSectionHeadersInRect:(CGRect)arg1;
- (id)indexPathsForItemsInRect:(CGRect)arg1 usingData:(id)arg2;
- (id)indexesForSectionFootersInRect:(CGRect)arg1 usingData:(id)arg2;
- (id)indexesForSectionHeadersInRect:(CGRect)arg1 usingData:(id)arg2;
- (CGSize)collectionViewContentSize;
- (id)invalidationContextForBoundsChange:(CGRect)arg1;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (id)init;
- (CGSize)synchronizeLayout;
- (id)finalLayoutAttributesForFooterInDeletedSection:(long long)arg1;
- (id)finalLayoutAttributesForHeaderInDeletedSection:(long long)arg1;
- (id)finalLayoutAttributesForDeletedItemAtIndexPath:(id)arg1;
- (id)initialLayoutAttributesForFooterInInsertedSection:(long long)arg1;
- (id)initialLayoutAttributesForHeaderInInsertedSection:(long long)arg1;
- (id)initialLayoutAttributesForInsertedItemAtIndexPath:(id)arg1;
- (void)finalizeCollectionViewUpdates;
@property (nonatomic, strong, setter=_setRowAlignmentsOptions:) NSDictionary *_rowAlignmentOptions;

@end

