//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXCollectionViewUpdateItem;

@interface UXCollectionViewUpdateGap : NSObject

+ (id)gapWithUpdateItem:(id)arg1;
@property (nonatomic) CGRect endingRect; // @synthesize endingRect=_endingRect;
@property (nonatomic) CGRect beginningRect; // @synthesize beginningRect=_beginningRect;
@property (nonatomic, readonly) NSArray *insertItems; // @synthesize insertItems=_insertItems;
@property (nonatomic, readonly) NSArray *deleteItems; // @synthesize deleteItems=_deleteItems;
@property (nonatomic, strong) UXCollectionViewUpdateItem *lastUpdateItem; // @synthesize lastUpdateItem=_lastUpdateItem;
@property (nonatomic, strong) UXCollectionViewUpdateItem *firstUpdateItem; // @synthesize firstUpdateItem=_firstUpdateItem;
@property (nonatomic, readonly) BOOL isSectionBasedGap;
@property (nonatomic, readonly) NSArray *updateItems;
@property (nonatomic, readonly) BOOL hasInserts;
@property (nonatomic, readonly) BOOL isDeleteBasedGap;
- (void)addUpdateItem:(id)arg1;
- (id)description;
- (id)init;

@end

