//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@class UXCollectionView, UXCollectionViewLayoutAttributes;

@interface UXCollectionReusableView : NSView

@property (nonatomic, copy, readonly) NSString *reuseIdentifier;
- (void)didTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (void)willTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (void)applyLayoutAttributes:(id)arg1;
- (void)prepareForReuse;
- (BOOL)wantsUpdateLayer;
- (id)initWithFrame:(CGRect)arg1;
- (BOOL)accessibilityPerformScrollToVisible;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (id)accessibilityRole;
- (id)accessibilityParent;

@end

