//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXView.h>

@interface UXImageView : UXView <NSAccessibilityImage>

@property (nonatomic, strong) NSImage *image;
- (void)sizeToFit;
- (void)setFrameSize:(CGSize)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidChangeBackingProperties;
- (CGSize)intrinsicContentSize;
- (id)initWithImage:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

