//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXView.h>

@interface UXImageView : UXView <NSAccessibilityImage>
{
    double _backingScaleFactor;
    CGSize _proposedSize;
    NSImage *_image;
}

@property (nonatomic, strong) NSImage *image; // @synthesize image=_image;
- (void)sizeToFit;
- (void)_updateBackingScaleFactorForWindow:(id)arg1;
- (void)_updateLayerContentsForWindow:(id)arg1;
- (CGSize)_proposedSize;
- (void)_setContentStretchInPixels:(CGRect)arg1 forContentSize:(CGSize)arg2 shouldTile:(BOOL)arg3;
- (void)setFrameSize:(CGSize)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidChangeBackingProperties;
- (CGSize)intrinsicContentSize;
- (id)initWithImage:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

