//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXView.h>

@interface UXLabel : UXView <NSAccessibilityStaticText>
{
    NSTextField *_concreteTextField;
    BOOL _highlighted;
    NSColor *_textColor;
    NSColor *_shadowColor;
    long long _numberOfLines;
    NSColor *_highlightedTextColor;
    CGSize _shadowOffset;
}

@property (nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property (nonatomic, strong) NSColor *highlightedTextColor; // @synthesize highlightedTextColor=_highlightedTextColor;
@property (nonatomic) long long numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property (nonatomic) CGSize shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property (nonatomic, strong) NSColor *shadowColor; // @synthesize shadowColor=_shadowColor;
@property (nonatomic, strong) NSColor *textColor; // @synthesize textColor=_textColor;
- (id)accessibilityRoleDescription;
- (void)setAccessibilityRoleDescription:(id)arg1;
- (id)accessibilityRole;
- (id)accessibilityLabel;
- (void)setAccessibilityLabel:(id)arg1;
- (id)accessibilityValue;
- (id)textFieldCell;
@property (nonatomic) BOOL selectable;
@property (nonatomic) BOOL centerVertically;
@property (nonatomic) double preferredMaxLayoutWidth;
@property (nonatomic) unsigned long long textAlignment;
@property (nonatomic) unsigned long long lineBreakMode;
@property (nonatomic, copy) NSAttributedString *attributedText;
@property (nonatomic, copy) NSString *text;
@property (nonatomic, strong) NSFont *font;
- (CGSize)intrinsicContentSize;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (void)sizeToFit;
- (void)setBackgroundColor:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

