//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXViewController.h>
#import <UXKit/UXToolbarDelegate-Protocol.h>

@class UXEventTracker, UXNavigationBar, UXToolbar;

@interface UXNavigationController : UXViewController <UXToolbarDelegate>

+ (id)keyPathsForValuesAffectingPreferredContentSize;
@property (nonatomic, readonly) UXEventTracker *interactivePopEventTracker; // @synthesize interactivePopEventTracker=_interactivePopEventTracker;
@property (nonatomic, weak)  id <UXNavigationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property (nonatomic, getter=isToolbarHidden) BOOL toolbarHidden; // @synthesize toolbarHidden=_toolbarHidden;
@property (nonatomic, getter=isNavigationBarDetached) BOOL navigationBarDetached; // @synthesize navigationBarDetached=_navigationBarDetached;
@property (nonatomic, getter=isNavigationBarHidden) BOOL navigationBarHidden; // @synthesize navigationBarHidden=_navigationBarHidden;
- (long long)positionForBar:(id)arg1;
- (id)popToViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (id)visibleViewController;
- (id)topViewController;
- (void)setViewControllers:(id)arg1 animated:(BOOL)arg2;
- (void)detachNavigationBar;
@property (nonatomic, readonly) UXToolbar *toolbar;
@property (nonatomic, readonly) UXToolbar *accessoryBar;
@property (nonatomic, readonly, getter=isAccessoryBarHidden) BOOL accessoryBarHidden;
@property (nonatomic, readonly) UXNavigationBar *navigationBar;
- (void)setToolbarHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setNavigationBarHidden:(BOOL)arg1 animated:(BOOL)arg2;
@property (nonatomic, copy) NSArray *viewControllers;
- (void)setEdgesForExtendedLayout:(unsigned long long)arg1;
- (id)transitionCoordinator;
- (void)invalidateIntrinsicLayoutInsets;
- (NSEdgeInsets)intrinsicLayoutInsets;
- (CGSize)preferredContentSize;
- (id)preferredFirstResponder;
- (void)updateViewConstraints;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)scrollWheel:(id)arg1;
- (BOOL)wantsForwardedScrollEventsForAxis:(long long)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithRootViewController:(id)arg1;

@end

