//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewFlowLayout.h>

// TODO get a definition for this
@protocol UXCollectionViewDelegateFlowLayout;

@interface UXTableLayout : UXCollectionViewFlowLayout

@property (nonatomic, readonly) NSMutableDictionary *headerAttributesByIndexPath; // @synthesize headerAttributesByIndexPath=_headerAttributesByIndexPath;
@property (nonatomic, readonly) NSMutableArray *layoutAttributesArray; // @synthesize layoutAttributesArray=_layoutAttributesArray;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(CGRect)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (id)invalidationContextForBoundsChange:(CGRect)arg1;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1;
- (void)prepareLayout;
- (BOOL)_wantsHeaderForSection:(unsigned long long)arg1;
- (NSEdgeInsets)insetForSection:(long long)arg1;
@property (nonatomic) BOOL showsSectionFooterForSingleSection;
@property (nonatomic) BOOL showsSectionHeaderForSingleSection;
@property (nonatomic) BOOL floatingHeadersDisabled;
@property (nonatomic, readonly) id <UXCollectionViewDelegateFlowLayout> delegateFlowLayout;
- (void)_setCollectionView:(id)arg1;
- (id)init;

@end

