//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewCell.h>

@class UXLabel, UXView, _UXButton;

@interface UXTableViewCell : UXCollectionViewCell

@property (nonatomic, readonly) UXView *internalHighlightedBackgroundView; // @synthesize internalHighlightedBackgroundView=_internalHighlightedBackgroundView;
@property (nonatomic) NSEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
@property (nonatomic) double indentationWidth; // @synthesize indentationWidth=_indentationWidth;
@property (nonatomic) long long indentationLevel; // @synthesize indentationLevel=_indentationLevel;
@property (nonatomic) long long selectionStyle; // @synthesize selectionStyle=_selectionStyle;
@property (nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property (nonatomic, strong) NSColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property (nonatomic, strong) UXView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property (nonatomic) long long accessoryType; // @synthesize accessoryType=_accessoryType;
@property (nonatomic, strong) UXLabel *detailTextLabel; // @synthesize detailTextLabel=_detailTextLabel;
@property (nonatomic, strong) UXLabel *textLabel; // @synthesize textLabel=_textLabel;
@property (nonatomic, strong) UXView *selectedBackgroundView; // @synthesize selectedBackgroundView=_selectedBackgroundView;
@property (nonatomic, strong) UXView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property (nonatomic) long long style; // @synthesize style=_style;
- (id)accessibilityLabel;
@property (nonatomic, readonly) UXView *lowerSpace;
@property (nonatomic, readonly) UXView *upperSpace;
@property (nonatomic, readonly) UXView *defaultSelectedBackgroundView;
@property (nonatomic, readonly) _UXButton *internalAccessoryView;
- (void)prepareForReuse;
- (void)setSelected:(BOOL)arg1;
- (void)updateConstraints;
- (void)viewDidMoveToWindow;
- (id)initWithFrame:(CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

