//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UXKit/UXCollectionViewController.h>

@class UXTableView;

@interface UXTableViewController : UXCollectionViewController

+ (Class)collectionViewClass;
@property (nonatomic, readonly) id <UXTableViewDelegate> tableViewDelegate;
- (id)preferredFirstResponder;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)didUpdateLayoutGuides;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) UXTableView *tableView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;

@end

