//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXViewController.h>

@interface UXTabBarController : UXViewController

@property (nonatomic, readonly) NSSegmentedControl *segmentedControl;
@property (nonatomic, weak) UXViewController *selectedViewController;
@property (nonatomic, copy) NSArray *viewControllers;
@property (nonatomic) unsigned long long selectedIndex;
- (void)viewDidLoad;
- (void)keyDown:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)segmentChanged:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

