//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UXKit/UXBar.h>

@interface UXToolbar : UXBar

@property (nonatomic, weak)  id <UXToolbarDelegate> delegate; // @synthesize delegate=_delegate;
- (long long)barPosition;
- (void)setItems:(id)arg1 animated:(BOOL)arg2;
- (void)mouseDown:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

