//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

@interface UXViewAnimationContext : NSObject

@property (nonatomic) double velocity;
@property (nonatomic) double damping;
@property (nonatomic) double stiffness;
@property (nonatomic) double mass;
- (void)generateSpringPropertiesForDuration:(double)arg1 damping:(double)arg2 velocity:(double)arg3;

@end

