//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>
#import <UXKit/UXCollectionViewFlowLayout.h>

// TODO get a definition for this
@protocol UXCollectionViewDelegateFlowLayout;

@interface UXTableLayout : UXCollectionViewFlowLayout

@property (nonatomic) BOOL showsSectionFooterForSingleSection;
@property (nonatomic) BOOL showsSectionHeaderForSingleSection;
@property (nonatomic) BOOL floatingHeadersDisabled;

@end

